use master;
-- Create Database for ChristBay Hospital CBH
DROP DATABASE IF EXISTS CBH;
GO
CREATE DATABASE CBH;
GO

USE CBH;

-- CREATE PATIENT TABLE
DROP TABLE IF EXISTS tblPATIENT;
GO
CREATE TABLE tblPATIENT (
    PATID INT PRIMARY KEY,
    FName NVARCHAR(50) NOT NULL,
    LName NVARCHAR(50) NOT NULL,
    MName NVARCHAR(50),
    Gender NVARCHAR(10),
    MStatus NVARCHAR(20),
    StateOfOrigin NVARCHAR(50),
    DateOfBirth DATE,
    PhoneNo NVARCHAR(20),
    EmailAddress NVARCHAR(100)
);

-- CREATE ADDRESS TABLE
DROP TABLE IF EXISTS tblADDRESS;
GO
CREATE TABLE tblADDRESS
(
    AddID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    PATID INT NOT NULL,
    HouseNo VARCHAR(10),
    StreetName NVARCHAR(255) NOT NULL,
    City NVARCHAR(50),
    State NVARCHAR(50),
    PostCode NVARCHAR(20),
    Country NVARCHAR(20),
    FOREIGN KEY (PATID) REFERENCES tblPATIENT(PATID)
);

-- NEXT OF KIN TABLE
DROP TABLE IF EXISTS tblNEXTOFKIN;
GO
CREATE TABLE tblNEXTOFKIN
(
    NOKID INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
    PATID INT NOT NULL,
    nxtFName NVARCHAR(50) NOT NULL,
    nxtLName NVARCHAR(50) NOT NULL,
    nxtRelationship NVARCHAR(50),
    nxtEmailAddress NVARCHAR(100),
    nxtPhoneNo NVARCHAR(20) NOT NULL,
    FOREIGN KEY (PATID) REFERENCES tblPATIENT(PATID)
);

-- Card Details TABLE
DROP TABLE IF EXISTS tblCard;
GO
CREATE TABLE tblCard
(
    RegID INT NOT NULL PRIMARY KEY,
    PATID INT NOT NULL,
    RegDate DATETIME,
    CardClass NVARCHAR(5) NOT NULL,
    CardType NVARCHAR(15),
    ShelveNo NVARCHAR(50),
    HMO NVARCHAR(50), 
    FOREIGN KEY (PATID) REFERENCES tblPATIENT(PATID)
);

-- Indexes for improving performance
CREATE INDEX idx_PATID_Address ON tblADDRESS(PATID);
CREATE INDEX idx_PATID_NextOfKin ON tblNEXTOFKIN(PATID);
CREATE INDEX idx_PATID_Card ON tblCard(PATID);
